
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    home: "Home",
    dashboard: "Dashboard",
    chatbot: "Chatbot",
    farmPlanning: "Farm Planning",
    diseaseDetection: "Disease Detection",
    education: "Education",
    weather: "Weather",
    marketplace: "Marketplace",
    government: "Government",
    profile: "Profile",
    support: "Support",
    contactUs: "Contact Us",
    
    // Common
    welcome: "Welcome",
    loading: "Loading",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    yes: "Yes",
    no: "No",
    
    // Home Page
    welcomeToKrishiSeva: "Welcome to Krishi Seva",
    empoweringFarmers: "Empowering farmers with technology, knowledge, and resources for sustainable agriculture",
    goToDashboard: "Go to Dashboard",
    learnMore: "Learn More",
    ourServices: "Our Services",
    comprehensiveSolutions: "Comprehensive solutions for modern agriculture",
    weatherForecast: "Weather Forecast",
    weatherForecastDesc: "Get accurate weather predictions for better farming decisions",
    diseaseDetectionDesc: "AI-powered crop disease identification and treatment suggestions",
    marketplaceDesc: "Buy and sell agricultural products directly with other farmers",
    farmEducationDesc: "Learn modern farming techniques and best practices",
    readyToTransform: "Ready to Transform Your Farming?",
    joinThousands: "Join thousands of farmers who are already benefiting from our platform",
    getStartedToday: "Get Started Today",
    
    // Stats
    activeFarmers: "Active Farmers",
    cropsMonitored: "Crops Monitored",
    yieldIncrease: "Yield Increase",
    successRate: "Success Rate",
    
    // Dashboard
    farmDashboard: "Farm Dashboard",
    monitorPerformance: "Monitor your farm's performance and activities",
    currentWeather: "Current Weather",
    temperature: "Temperature",
    humidity: "Humidity",
    rainfall: "Rainfall",
    condition: "Condition",
    totalCrops: "Total Crops",
    healthyPlants: "Healthy Plants",
    alerts: "Alerts",
    marketOrders: "Market Orders",
    recentActivities: "Recent Activities",
    upcomingTasks: "Upcoming Tasks",
    
    // Weather
    weatherForecastTitle: "Weather Forecast",
    stayUpdated: "Stay updated with weather conditions for better farm planning",
    searchLocation: "Search location...",
    sevenDayForecast: "7-Day Forecast",
    farmingRecommendations: "Farming Recommendations",
    weatherAlerts: "Weather Alerts",
    windSpeed: "Wind Speed",
    visibility: "Visibility",
    uvIndex: "UV Index",
    feelsLike: "Feels like",
    
    // Days
    "day.today": "Today",
    "day.tomorrow": "Tomorrow",
    "day.wednesday": "Wednesday",
    "day.thursday": "Thursday",
    "day.friday": "Friday",
    "day.saturday": "Saturday",
    "day.sunday": "Sunday",
    
    // Weather Conditions
    "condition.sunny": "Sunny",
    "condition.cloudy": "Cloudy",
    "condition.partlyCloudy": "Partly Cloudy",
    "condition.rainy": "Rainy",
    
    // Advice
    "advice.irrigationTitle": "Irrigation Recommendation",
    "advice.irrigationText": "Based on current soil moisture and weather forecast, irrigation is recommended for optimal crop growth.",
    "advice.pestAlertTitle": "Pest Alert",
    "advice.pestAlertText": "High humidity levels may increase pest activity. Monitor crops closely and consider preventive measures.",
    "advice.harvestWindowTitle": "Harvest Window",
    "advice.harvestWindowText": "Favorable weather conditions expected. Good time for harvesting ready crops.",
    "advice.fertilizerApplicationTitle": "Fertilizer Application",
    "advice.fertilizerApplicationText": "Weather conditions are suitable for fertilizer application. Apply before expected rainfall.",
    
    // Weather Alerts
    "heavyRainAlertTitle": "Heavy Rain Alert",
    "heavyRainAlertAdvice": "Heavy rainfall expected in the next 48 hours. Ensure proper drainage and protect sensitive crops.",
    
    // Language
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिंदी",
    malayalam: "മലയാളം",
    
    // Farm Planning
    farmPlanningTitle: "Farm Planning",
    farmPlanningDesc: "Plan your crops and farming activities for optimal yield",
    planningProcess: "Planning Process",
    soilAnalysis: "Soil Analysis",
    soilAnalysisDesc: "Test soil pH, nutrients, and organic matter content",
    cropSelection: "Crop Selection",
    cropSelectionDesc: "Choose crops based on soil type and climate",
    resourcePlanning: "Resource Planning",
    resourcePlanningDesc: "Plan water, fertilizers, and equipment needs",
    scheduleCreation: "Schedule Creation",
    scheduleCreationDesc: "Create planting, care, and harvest schedules",
    completed: "Completed",
    inProgress: "In Progress",
    pending: "Pending",
    selectCrop: "Select Crop",
    chooseCrop: "Choose a crop",
    selectSeason: "Select season",
    season: "Season",
    kharifMonsoon: "Kharif (Monsoon)",
    rabiWinter: "Rabi (Winter)",
    zaidSummer: "Zaid (Summer)",
    generatePlan: "Generate Plan",
    cropInformation: "Crop Information",
    duration: "Duration",
    expectedYield: "Expected Yield",
    farmingCalendar: "Farming Calendar",
    plantingSeason: "Planting Season",
    growingSeason: "Growing Season",
    harvestSeason: "Harvest Season",
    careMaintenance: "Care & Maintenance",
    harvestStorage: "Harvest & Storage",
    
    // Disease Detection
    diseaseDetectionTitle: "Disease Detection",
    diseaseDetectionPageDesc: "Upload plant images for AI-powered disease identification",
    uploadPlantImage: "Upload Plant Image",
    clickUploadDrag: "Click to upload or drag and drop",
    pngJpgLimit: "PNG, JPG up to 10MB",
    imageSelectedSuccessfully: "Image selected successfully",
    analyzeDisease: "Analyze Disease",
    analyzing: "Analyzing...",
    analysisResults: "Analysis Results",
    confidence: "Confidence",
    crop: "Crop",
    symptoms: "Symptoms",
    treatment: "Treatment",
    prevention: "Prevention",
    uploadImageForAnalysis: "Upload an image to get disease analysis results",
    commonDiseases: "Common Diseases",
    severity: "Severity",
    high: "High",
    medium: "Medium",
    low: "Low",
    
    // Education
    farmEducationTitle: "Farm Education",
    learnModernFarming: "Learn modern farming techniques and best practices",
    courseCompletion: "Course Completion",
    certificatesEarned: "Certificates Earned",
    studyHours: "Study Hours",
    communityRank: "Community Rank",
    searchCourses: "Search courses...",
    allCourses: "All Courses",
    cropManagement: "Crop Management",
    technology: "Technology",
    sustainability: "Sustainability",
    soilScience: "Soil Science",
    irrigation: "Irrigation",
    diseaseControl: "Disease Control",
    students: "students",
    startLearning: "Start Learning",
    joinExpertWebinar: "Join Our Expert Webinar",
    futureOfAgriculture: "Future of Agriculture: Technology and Sustainability",
    liveSessionExperts: "Live session with industry experts • Tomorrow at 2:00 PM",
    registerNow: "Register Now",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    
    // Marketplace
    marketplaceTitle: "Marketplace",
    buyAndSellProducts: "Buy and sell agricultural products directly with farmers",
    buyProducts: "Buy Products",
    myListings: "My Listings",
    searchProducts: "Search products...",
    all: "All",
    grains: "Grains",
    vegetables: "Vegetables",
    fruits: "Fruits",
    pulses: "Pulses",
    spices: "Spices",
    perKg: "per kg",
    addToCart: "Add to Cart",
    outOfStock: "Out of Stock",
    myProductListings: "My Product Listings",
    addNewProduct: "Add New Product",
    views: "Views",
    inquiries: "Inquiries",
    editListing: "Edit Listing",
    viewAnalytics: "View Analytics",
    salesOverview: "Sales Overview",
    activeListings: "Active Listings",
    totalViews: "Total Views",
    revenueThisMonth: "Revenue This Month",
    
    // Government
    governmentSchemesTitle: "Government Schemes",
    accessGovernmentPrograms: "Access government programs and financial assistance for farmers",
    myApplications: "My Applications",
    applicationId: "Application ID",
    submitted: "Submitted",
    approved: "Approved",
    processing: "Processing",
    amount: "Amount",
    deadline: "Deadline",
    eligibility: "Eligibility",
    keyBenefits: "Key Benefits",
    applyNow: "Apply Now",
    quickLinks: "Quick Links",
    allSchemes: "All Schemes",
    subsidies: "Subsidies",
    insurance: "Insurance",
    credit: "Credit",
    marketSupport: "Market",
    limitedTime: "Limited Time",
    
    // Profile
    myProfile: "My Profile",
    manageAccountInfo: "Manage your account information and farming details",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    personalInformation: "Personal Information",
    memberSince: "Member since",
    verifiedFarmer: "Verified Farmer",
    fullName: "Full Name",
    yourFirstName: "Your first name",
    yourLastName: "Your last name",
    email: "Email",
    phone: "Phone",
    farmSize: "Farm Size",
    location: "Location",
    mainCrops: "Main Crops",
    experience: "Experience",
    achievements: "Achievements",
    bestFarmerAward: "Best Farmer Award",
    organicCertification: "Organic Certification",
    highYieldAchievement: "High Yield Achievement",
    performanceStatistics: "Performance Statistics",
    totalHarvest: "Total Harvest",
    thisYear: "This year",
    revenue: "Revenue",
    coursesCompleted: "Courses Completed",
    allTime: "All time",
    recentActivitiesProfile: "Recent Activities",
    
    // Support
    supportCenter: "Support Center",
    getHelpAndAnswers: "Get help and find answers to your questions",
    phoneSupport: "Phone Support",
    getImmediateHelp: "Get immediate help from our experts",
    available24x7: "24/7 Available",
    emailSupport: "Email Support",
    sendDetailedQueries: "Send us detailed queries",
    responseWithin24h: "Response within 24 hours",
    liveChat: "Live Chat",
    chatWithSupportTeam: "Chat with our support team",
    startChat: "Start Chat",
    businessHours: "9 AM - 6 PM IST",
    faq: "FAQ",
    myTickets: "My Tickets",
    createTicket: "Create Ticket",
    searchFaq: "Search frequently asked questions...",
    mySupportTickets: "My Support Tickets",
    ticketId: "Ticket ID",
    created: "Created",
    lastUpdated: "Last updated",
    createSupportTicket: "Create Support Ticket",
    subject: "Subject",
    briefDescription: "Brief description of your issue",
    category: "Category",
    selectCategory: "Select a category",
    technicalIssue: "Technical Issue",
    billing: "Billing",
    featureRequest: "Feature Request",
    generalInquiry: "General Inquiry",
    priority: "Priority",
    description: "Description",
    describeIssueDetail: "Please describe your issue in detail...",
    open: "Open",
    resolved: "Resolved",
    
    // Contact Us
    contactUsTitle: "Contact Us",
    getInTouchWithTeam: "Get in touch with our team for support and inquiries",
    sendMessage: "Send us a Message",
    firstName: "First Name",
    lastName: "Last Name",
    yourEmail: "your.email@example.com",
    phoneNumber: "+91 XXXXX XXXXX",
    messageSubject: "What is your message about?",
    messageText: "Tell us how we can help you...",
    sendMessageBtn: "Send Message",
    contactInformation: "Contact Information",
    headquarters: "Headquarters",
    phoneSupportContact: "Phone Support",
    emailSupportContact: "Email Support",
    businessHoursContact: "Business Hours",
    meetOurTeam: "Meet Our Team",
    emergencySupport: "Emergency Agricultural Support",
    urgentFarmingEmergencies: "For urgent farming emergencies and disasters",
    emergencyHotline: "Emergency Hotline: 1800-XXX-EMERGENCY",
    findUs: "Find Us",
    interactiveMapComingSoon: "Interactive map coming soon",
    
    // Chatbot
    chatbotTitle: "Krishi AI Assistant",
    onlineReadyToHelp: "Online • Ready to help",
    krishiAiGreeting: "Hello! I'm Krishi AI, your agricultural assistant. How can I help you today?",
    weatherUpdate: "Weather update",
    cropAdvice: "Crop advice",
    marketPrices: "Market prices",
    diseaseHelp: "Disease help",
    askAnything: "Ask me anything about farming...",
    farmingTips: "Farming tips",
    
    // Registration
    completeProfile: "Complete Your Profile",
    personalizeExperience: "Tell us about yourself to personalize your Krishi Seva experience",
    profileSetup: "Profile Setup",
    chooseYourRole: "Choose Your Role",
    farmer: "Farmer",
    admin: "Admin",
    retailer: "Retailer",
    labourer: "Labourer",
    agriculturalProducer: "Agricultural producer and cultivator",
    systemAdministrator: "System administrator and manager",
    businessOwnerSeller: "Business owner and seller",
    agriculturalWorker: "Agricultural worker and assistant",
    profileUpdatedSuccessfully: "Profile updated successfully! Your information has been saved.",
    errorUpdatingProfile: "There was an error updating your profile. Please try again.",
    emailRequired: "Email is required",
    validEmailRequired: "Please enter a valid email address",
    phoneRequired: "Phone number is required",
    businessNameRequired: "Business name is required",
    businessTypeRequired: "Business type is required",
    farmerNameRequired: "name is required",
    savingProfile: "Saving Profile...",
    saveProfile: "Save Profile",
  },
  
  hi: {
    // Navigation
    home: "होम",
    dashboard: "डैशबोर्ड",
    chatbot: "चैटबॉट",
    farmPlanning: "खेती की योजना",
    diseaseDetection: "रोग पहचान",
    education: "शिक्षा",
    weather: "मौसम",
    marketplace: "बाजार",
    government: "सरकारी योजनाएं",
    profile: "प्रोफाइल",
    support: "सहायता",
    contactUs: "संपर्क करें",
    
    // Common
    welcome: "स्वागत",
    loading: "लोड हो रहा है",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सेव करें",
    edit: "संपादित करें",
    delete: "मिटाएं",
    search: "खोजें",
    filter: "फिल्टर",
    apply: "लागू करें",
    close: "बंद करें",
    back: "वापस",
    next: "आगे",
    previous: "पिछला",
    yes: "हां",
    no: "नहीं",
    
    // Home Page
    welcomeToKrishiSeva: "कृषि सेवा में आपका स्वागत है",
    empoweringFarmers: "टिकाऊ कृषि के लिए किसानों को तकनीक, ज्ञान और संसाधनों से सशक्त बनाना",
    goToDashboard: "डैशबोर्ड पर जाएं",
    learnMore: "और जानें",
    ourServices: "हमारी सेवाएं",
    comprehensiveSolutions: "आधुनिक कृषि के लिए व्यापक समाधान",
    weatherForecast: "मौसम पूर्वानुमान",
    weatherForecastDesc: "बेहतर खेती के फैसलों के लिए सटीक मौसम भविष्यवाणी प्राप्त करें",
    diseaseDetectionDesc: "AI-संचालित फसल रोग पहचान और उपचार सुझाव",
    marketplaceDesc: "अन्य किसानों के साथ सीधे कृषि उत्पाद खरीदें और बेचें",
    farmEducationDesc: "आधुनिक खेती की तकनीक और सर्वोत्तम प्रथाएं सीखें",
    readyToTransform: "अपनी खेती को बदलने के लिए तैयार हैं?",
    joinThousands: "हजारों किसानों के साथ जुड़ें जो पहले से ही हमारे प्लेटफॉर्म से लाभान्वित हो रहे हैं",
    getStartedToday: "आज ही शुरू करें",
    
    // Stats
    activeFarmers: "सक्रिय किसान",
    cropsMonitored: "निगरानी की गई फसलें",
    yieldIncrease: "उत्पादन वृद्धि",
    successRate: "सफलता दर",
    
    // Dashboard
    farmDashboard: "फार्म डैशबोर्ड",
    monitorPerformance: "अपने खेत के प्रदर्शन और गतिविधियों की निगरानी करें",
    currentWeather: "वर्तमान मौसम",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    rainfall: "वर्षा",
    condition: "स्थिति",
    totalCrops: "कुल फसलें",
    healthyPlants: "स्वस्थ पौधे",
    alerts: "चेतावनियां",
    marketOrders: "बाजार के आर्डर",
    recentActivities: "हाल की गतिविधियां",
    upcomingTasks: "आगामी कार्य",
    
    // Weather
    weatherForecastTitle: "मौसम पूर्वानुमान",
    stayUpdated: "बेहतर खेत की योजना के लिए मौसम की स्थिति से अपडेट रहें",
    searchLocation: "स्थान खोजें...",
    sevenDayForecast: "7-दिन का पूर्वानुमान",
    farmingRecommendations: "खेती की सिफारिशें",
    weatherAlerts: "मौसम चेतावनियां",
    windSpeed: "हवा की गति",
    visibility: "दृश्यता",
    uvIndex: "यूवी सूचकांक",
    feelsLike: "महसूस होता है",
    
    // Days
    "day.today": "आज",
    "day.tomorrow": "कल",
    "day.wednesday": "बुधवार",
    "day.thursday": "गुरुवार",
    "day.friday": "शुक्रवार",
    "day.saturday": "शनिवार",
    "day.sunday": "रविवार",
    
    // Weather Conditions
    "condition.sunny": "धूप",
    "condition.cloudy": "बादल",
    "condition.partlyCloudy": "आंशिक बादल",
    "condition.rainy": "बारिश",
    
    // Advice
    "advice.irrigationTitle": "सिंचाई की सिफारिश",
    "advice.irrigationText": "मिट्टी की नमी और मौसम पूर्वानुमान के आधार पर, फसल की बेहतर वृद्धि के लिए सिंचाई की सिफारिश की जाती है।",
    "advice.pestAlertTitle": "कीट चेतावनी",
    "advice.pestAlertText": "उच्च आर्द्रता के स्तर से कीट गतिविधि बढ़ सकती है। फसलों पर बारीकी से नजर रखें और निवारक उपायों पर विचार करें।",
    "advice.harvestWindowTitle": "फसल कटाई का समय",
    "advice.harvestWindowText": "अनुकूल मौसम की स्थिति की उम्मीद है। तैयार फसलों की कटाई के लिए अच्छा समय है।",
    "advice.fertilizerApplicationTitle": "उर्वरक का प्रयोग",
    "advice.fertilizerApplicationText": "मौसम की स्थिति उर्वरक के प्रयोग के लिए उपयुक्त है। अपेक्षित वर्षा से पहले लागू करें।",
    
    // Weather Alerts
    "heavyRainAlertTitle": "भारी बारिश की चेतावनी",
    "heavyRainAlertAdvice": "अगले 48 घंटों में भारी बारिश की उम्मीद है। उचित जल निकासी सुनिश्चित करें और संवेदनशील फसलों की सुरक्षा करें।",
    
    // Language
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिंदी",
    malayalam: "മലയാളം",
    
    // Farm Planning
    farmPlanningTitle: "खेती की योजना",
    farmPlanningDesc: "बेहतर उत्पादन के लिए अपनी फसलों और खेती की गतिविधियों की योजना बनाएं",
    planningProcess: "योजना प्रक्रिया",
    soilAnalysis: "मिट्टी विश्लेषण",
    soilAnalysisDesc: "मिट्टी का पीएच, पोषक तत्व और जैविक पदार्थ की जांच करें",
    cropSelection: "फसल चयन",
    cropSelectionDesc: "मिट्टी के प्रकार और जलवायु के आधार पर फसल चुनें",
    resourcePlanning: "संसाधन योजना",
    resourcePlanningDesc: "पानी, उर्वरक और उपकरणों की आवश्यकताओं की योजना बनाएं",
    scheduleCreation: "अनुसूची निर्माण",
    scheduleCreationDesc: "रोपण, देखभाल और फसल की कटाई की अनुसूची बनाएं",
    completed: "पूर्ण",
    inProgress: "प्रगति में",
    pending: "लंबित",
    selectCrop: "फसल चुनें",
    chooseCrop: "एक फसल चुनें",
    selectSeason: "मौसम चुनें",
    season: "मौसम",
    kharifMonsoon: "खरीफ (मानसून)",
    rabiWinter: "रबी (सर्दी)",
    zaidSummer: "जायद (गर्मी)",
    generatePlan: "योजना बनाएं",
    cropInformation: "फसल की जानकारी",
    duration: "अवधि",
    expectedYield: "अपेक्षित उत्पादन",
    farmingCalendar: "खेती का कैलेंडर",
    plantingSeason: "बुआई का मौसम",
    growingSeason: "बढ़ने का मौसम",
    harvestSeason: "कटाई का मौसम",
    careMaintenance: "देखभाल और रखरखाव",
    harvestStorage: "फसल कटाई और भंडारण",
    
    // Disease Detection
    diseaseDetectionTitle: "रोग पहचान",
    diseaseDetectionPageDesc: "AI-संचालित रोग पहचान के लिए पौधों की तस्वीरें अपलोड करें",
    uploadPlantImage: "पौधे की तस्वीर अपलोड करें",
    clickUploadDrag: "अपलोड करने के लिए क्लिक करें या ड्रैग करें",
    pngJpgLimit: "PNG, JPG 10MB तक",
    imageSelectedSuccessfully: "छवि सफलतापूर्वक चुनी गई",
    analyzeDisease: "रोग का विश्लेषण करें",
    analyzing: "विश्लेषण हो रहा है...",
    analysisResults: "विश्लेषण के परिणाम",
    confidence: "विश्वास",
    crop: "फसल",
    symptoms: "लक्षण",
    treatment: "उपचार",
    prevention: "रोकथाम",
    uploadImageForAnalysis: "रोग विश्लेषण के परिणाम प्राप्त करने के लिए एक छवि अपलोड करें",
    commonDiseases: "आम बीमारियां",
    severity: "गंभीरता",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    
    // Education
    farmEducationTitle: "कृषि शिक्षा",
    learnModernFarming: "आधुनिक खेती की तकनीकें और सर्वोत्तम प्रथाएं सीखें",
    courseCompletion: "पाठ्यक्रम पूर्णता",
    certificatesEarned: "अर्जित प्रमाणपत्र",
    studyHours: "अध्ययन घंटे",
    communityRank: "समुदायिक रैंक",
    searchCourses: "कोर्स खोजें...",
    allCourses: "सभी कोर्स",
    cropManagement: "फसल प्रबंधन",
    technology: "प्रौद्योगिकी",
    sustainability: "स्थिरता",
    soilScience: "मृदा विज्ञान",
    irrigation: "सिंचाई",
    diseaseControl: "रोग नियंत्रण",
    students: "छात्र",
    startLearning: "सीखना शुरू करें",
    joinExpertWebinar: "हमारे विशेषज्ञ वेबिनार में शामिल हों",
    futureOfAgriculture: "कृषि का भविष्य: प्रौद्योगिकी और स्थिरता",
    liveSessionExperts: "उद्योग विशेषज्ञों के साथ लाइव सेशन • कल दोपहर 2:00 बजे",
    registerNow: "अभी पंजीकरण करें",
    beginner: "शुरुआती",
    intermediate: "मध्यम",
    advanced: "उन्नत",
    
    // Marketplace
    marketplaceTitle: "बाजार",
    buyAndSellProducts: "किसानों के साथ सीधे कृषि उत्पाद खरीदें और बेचें",
    buyProducts: "उत्पाद खरीदें",
    myListings: "मेरी लिस्टिंग",
    searchProducts: "उत्पाद खोजें...",
    all: "सभी",
    grains: "अनाज",
    vegetables: "सब्जियां",
    fruits: "फल",
    pulses: "दालें",
    spices: "मसाले",
    perKg: "प्रति किलो",
    addToCart: "कार्ट में जोड़ें",
    outOfStock: "स्टॉक में नहीं",
    myProductListings: "मेरी उत्पाद सूची",
    addNewProduct: "नया उत्पाद जोड़ें",
    views: "देखे गए",
    inquiries: "पूछताछ",
    editListing: "लिस्टिंग संपादित करें",
    viewAnalytics: "एनालिटिक्स देखें",
    salesOverview: "बिक्री अवलोकन",
    activeListings: "सक्रिय लिस्टिंग",
    totalViews: "कुल दृश्य",
    revenueThisMonth: "इस महीने की आय",
    
    // Government
    governmentSchemesTitle: "सरकारी योजनाएं",
    accessGovernmentPrograms: "किसानों के लिए सरकारी कार्यक्रमों और वित्तीय सहायता तक पहुंच",
    myApplications: "मेरे आवेदन",
    applicationId: "आवेदन संख्या",
    submitted: "जमा किया गया",
    approved: "स्वीकृत",
    processing: "प्रसंस्करण",
    amount: "राशि",
    deadline: "अंतिम तिथि",
    eligibility: "पात्रता",
    keyBenefits: "मुख्य लाभ",
    applyNow: "अभी आवेदन करें",
    quickLinks: "त्वरित लिंक",
    allSchemes: "सभी योजनाएं",
    subsidies: "सब्सिडी",
    insurance: "बीमा",
    credit: "ऋण",
    marketSupport: "बाजार",
    limitedTime: "सीमित समय",
    
    // Profile
    myProfile: "मेरी प्रोफाइल",
    manageAccountInfo: "अपनी खाता जानकारी और खेती के विवरण प्रबंधित करें",
    editProfile: "प्रोफाइल संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    personalInformation: "व्यक्तिगत जानकारी",
    memberSince: "सदस्य बने",
    verifiedFarmer: "सत्यापित किसान",
    fullName: "पूरा नाम",
    yourFirstName: "आपका पहला नाम",
    yourLastName: "आपका अंतिम नाम",
    email: "ईमेल",
    phone: "फोन",
    farmSize: "खेत का आकार",
    location: "स्थान",
    mainCrops: "मुख्य फसलें",
    experience: "अनुभव",
    achievements: "उपलब्धियां",
    bestFarmerAward: "सर्वश्रेष्ठ किसान पुरस्कार",
    organicCertification: "जैविक प्रमाणन",
    highYieldAchievement: "उच्च उत्पादन उपलब्धि",
    performanceStatistics: "प्रदर्शन सांख्यिकी",
    totalHarvest: "कुल फसल",
    thisYear: "इस वर्ष",
    revenue: "आय",
    coursesCompleted: "पूर्ण किए गए कोर्स",
    allTime: "सभी समय",
    recentActivitiesProfile: "हाल की गतिविधियां",
    
    // Support
    supportCenter: "सहायता केंद्र",
    getHelpAndAnswers: "सहायता प्राप्त करें और अपने प्रश्नों के उत्तर पाएं",
    phoneSupport: "फोन सहायता",
    getImmediateHelp: "हमारे विशेषज्ञों से तत्काल सहायता प्राप्त करें",
    available24x7: "24/7 उपलब्ध",
    emailSupport: "ईमेल सहायता",
    sendDetailedQueries: "हमें विस्तृत प्रश्न भेजें",
    responseWithin24h: "24 घंटे के भीतर जवाब",
    liveChat: "लाइव चैट",
    chatWithSupportTeam: "हमारी सहायता टीम के साथ चैट करें",
    startChat: "चैट शुरू करें",
    businessHours: "सुबह 9 - शाम 6 बजे IST",
    faq: "FAQ",
    myTickets: "मेरे टिकट",
    createTicket: "टिकट बनाएं",
    searchFaq: "अक्सर पूछे जाने वाले प्रश्न खोजें...",
    mySupportTickets: "मेरे सहायता टिकट",
    ticketId: "टिकट संख्या",
    created: "बनाया गया",
    lastUpdated: "अंतिम अपडेट",
    createSupportTicket: "सहायता टिकट बनाएं",
    subject: "विषय",
    briefDescription: "आपकी समस्या का संक्षिप्त विवरण",
    category: "श्रेणी",
    selectCategory: "एक श्रेणी चुनें",
    technicalIssue: "तकनीकी समस्या",
    billing: "बिलिंग",
    featureRequest: "फीचर अनुरोध",
    generalInquiry: "सामान्य जांच",
    priority: "प्राथमिकता",
    description: "विवरण",
    describeIssueDetail: "कृपया अपनी समस्या का विस्तार से वर्णन करें...",
    open: "खुला",
    resolved: "हल",
    
    // Contact Us
    contactUsTitle: "संपर्क करें",
    getInTouchWithTeam: "सहायता और पूछताछ के लिए हमारी टीम से संपर्क करें",
    sendMessage: "हमें संदेश भेजें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    yourEmail: "आपका.ईमेल@उदाहरण.कॉम",
    phoneNumber: "+91 XXXXX XXXXX",
    messageSubject: "आपका संदेश किस बारे में है?",
    messageText: "हमें बताएं कि हम आपकी कैसे सहायता कर सकते हैं...",
    sendMessageBtn: "संदेश भेजें",
    contactInformation: "संपर्क जानकारी",
    headquarters: "मुख्यालय",
    phoneSupportContact: "फोन सहायता",
    emailSupportContact: "ईमेल सहायता",
    businessHoursContact: "व्यावसायिक घंटे",
    meetOurTeam: "हमारी टीम से मिलें",
    emergencySupport: "आपातकालीन कृषि सहायता",
    urgentFarmingEmergencies: "तत्काल खेती की आपात स्थितियों और आपदाओं के लिए",
    emergencyHotline: "आपातकालीन हॉटलाइन: 1800-XXX-EMERGENCY",
    findUs: "हमें खोजें",
    interactiveMapComingSoon: "इंटरैक्टिव मानचित्र जल्द आ रहा है",
    
    // Chatbot
    chatbotTitle: "कृषि AI सहायक",
    onlineReadyToHelp: "ऑनलाइन • सहायता के लिए तैयार",
    krishiAiGreeting: "नमस्ते! मैं कृषि AI हूं, आपका कृषि सहायक। आज मैं आपकी कैसे सहायता कर सकता हूं?",
    weatherUpdate: "मौसम अपडेट",
    cropAdvice: "फसल सलाह",
    marketPrices: "बाजार मूल्य",
    diseaseHelp: "रोग सहायता",
    askAnything: "खेती के बारे में कुछ भी पूछें...",
    farmingTips: "खेती के टिप्स",
    
    // Registration
    completeProfile: "अपनी प्रोफाइल पूरी करें",
    personalizeExperience: "अपने कृषि सेवा अनुभव को व्यक्तिगत बनाने के लिए हमें अपने बारे में बताएं",
    profileSetup: "प्रोफाइल सेटअप",
    chooseYourRole: "अपनी भूमिका चुनें",
    farmer: "किसान",
    admin: "प्रशासक",
    retailer: "खुदरा विक्रेता",
    labourer: "मजदूर",
    agriculturalProducer: "कृषि उत्पादक और खेती करने वाला",
    systemAdministrator: "सिस्टम प्रशासक और प्रबंधक",
    businessOwnerSeller: "व्यापारी और विक्रेता",
    agriculturalWorker: "कृषि कार्यकर्ता और सहायक",
    profileUpdatedSuccessfully: "प्रोफाइल सफलतापूर्वक अपडेट हो गई! आपकी जानकारी सहेज दी गई है।",
    errorUpdatingProfile: "आपकी प्रोफाइल अपडेट करने में त्रुटि हुई। कृपया पुनः प्रयास करें।",
    emailRequired: "ईमेल आवश्यक है",
    validEmailRequired: "कृपया एक वैध ईमेल पता दर्ज करें",
    phoneRequired: "फोन नंबर आवश्यक है",
    businessNameRequired: "व्यापार का नाम आवश्यक है",
    businessTypeRequired: "व्यापार का प्रकार आवश्यक है",
    farmerNameRequired: "नाम आवश्यक है",
    savingProfile: "प्रोफाइल सहेजा जा रहा है...",
    saveProfile: "प्रोफाइल सेव करें",
  },
  
  ml: {
    // Navigation
    home: "ഹോം",
    dashboard: "ഡാഷ്ബോർഡ്",
    chatbot: "ചാറ്റ്ബോട്ട്",
    farmPlanning: "കൃഷി ആസൂത്രണം",
    diseaseDetection: "രോഗ കണ്ടെത്തൽ",
    education: "വിദ്യാഭ്യാസം",
    weather: "കാലാവസ്ഥ",
    marketplace: "മാർക്കറ്റ്പ്ലേസ്",
    government: "സർക്കാർ പദ്ധതികൾ",
    profile: "പ്രൊഫൈൽ",
    support: "പിന്തുണ",
    contactUs: "ബന്ധപ്പെടുക",
    
    // Common
    welcome: "സ്വാഗതം",
    loading: "ലോഡിംഗ്",
    submit: "സമർപ്പിക്കുക",
    cancel: "റദ്ദാക്കുക",
    save: "സേവ് ചെയ്യുക",
    edit: "എഡിറ്റ് ചെയ്യുക",
    delete: "ഇല്ലാതാക്കുക",
    search: "തിരയുക",
    filter: "ഫിൽട്ടർ",
    apply: "പ്രയോഗിക്കുക",
    close: "അടയ്ക്കുക",
    back: "പിന്നോട്ട്",
    next: "അടുത്തത്",
    previous: "മുമ്പത്തെ",
    yes: "അതെ",
    no: "ഇല്ല",
    
    // Home Page
    welcomeToKrishiSeva: "കൃഷി സേവയിലേക്ക് സ്വാഗതം",
    empoweringFarmers: "സുസ്ഥിര കൃഷിക്കായി സാങ്കേതികവിദ്യ, അറിവ്, വിഭവങ്ങൾ എന്നിവ ഉപയോഗിച്ച് കർഷകരെ ശാക്തീകരിക്കുന്നു",
    goToDashboard: "ഡാഷ്ബോർഡിലേക്ക് പോകുക",
    learnMore: "കൂടുതൽ അറിയുക",
    ourServices: "ഞങ്ങളുടെ സേവനങ്ങൾ",
    comprehensiveSolutions: "ആധുനിക കൃഷിക്കായുള്ള സമ്പൂർണ്ണ പരിഹാരങ്ങൾ",
    weatherForecast: "കാലാവസ്ഥ പ്രവചനം",
    weatherForecastDesc: "മികച്ച കൃഷി തീരുമാനങ്ങൾക്കായി കൃത്യമായ കാലാവസ്ഥാ പ്രവചനങ്ങൾ നേടുക",
    diseaseDetectionDesc: "AI-പവർഡ് വിള രോഗ തിരിച്ചറിയൽ, ചികിത്സാ നിർദ്ദേശങ്ങൾ",
    marketplaceDesc: "മറ്റ് കർഷകരുമായി നേരിട്ട് കാർഷിക ഉൽപ്പന്നങ്ങൾ വാങ്ങുകയും വിൽക്കുകയും ചെയ്യുക",
    farmEducationDesc: "ആധുനിക കൃഷി സാങ്കേതികതകളും മികച്ച രീതികളും പഠിക്കുക",
    readyToTransform: "നിങ്ങളുടെ കൃഷിയെ മാറ്റാൻ തയ്യാറാണോ?",
    joinThousands: "ഞങ്ങളുടെ പ്ലാറ്റ്ഫോമിൽ നിന്ന് ഗുണം നേടുന്ന ആയിരക്കണക്കിന് കർഷകരോട് ചേരുക",
    getStartedToday: "ഇന്നുതന്നെ ആരംഭിക്കുക",
    
    // Stats
    activeFarmers: "സജീവ കർഷകർ",
    cropsMonitored: "നിരീക്ഷിച്ച വിളകൾ",
    yieldIncrease: "വിളവ് വർദ്ധനവ്",
    successRate: "വിജയ നിരക്ക്",
    
    // Dashboard
    farmDashboard: "ഫാം ഡാഷ്ബോർഡ്",
    monitorPerformance: "നിങ്ങളുടെ കൃഷിയുടെ പ്രകടനവും പ്രവർത്തനങ്ങളും നിരീക്ഷിക്കുക",
    currentWeather: "നിലവിലെ കാലാവസ്ഥ",
    temperature: "താപനില",
    humidity: "ആർദ്രത",
    rainfall: "മഴ",
    condition: "അവസ്ഥ",
    totalCrops: "ആകെ വിളകൾ",
    healthyPlants: "ആരോഗ്യകരമായ ചെടികൾ",
    alerts: "മുന്നറിയിപ്പുകൾ",
    marketOrders: "മാർക്കറ്റ് ഓർഡറുകൾ",
    recentActivities: "സമീപകാല പ്രവർത്തനങ്ങൾ",
    upcomingTasks: "വരാനിരിക്കുന്ന ജോലികൾ",
    
    // Weather
    weatherForecastTitle: "കാലാവസ്ഥാ പ്രവചനം",
    stayUpdated: "മികച്ച കൃഷി ആസൂത്രണത്തിനായി കാലാവസ്ഥാ വ്യവസ്ഥകളിൽ അപ്ഡേറ്റ് ആയിരിക്കുക",
    searchLocation: "സ്ഥലം തിരയുക...",
    sevenDayForecast: "7-ദിവസത്തെ പ്രവചനം",
    farmingRecommendations: "കൃഷി നിർദ്ദേശങ്ങൾ",
    weatherAlerts: "കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ",
    windSpeed: "കാറ്റിന്റെ വേഗത",
    visibility: "ദൃശ്യപരത",
    uvIndex: "യുവി സൂചിക",
    feelsLike: "തോന്നുന്നത്",
    
    // Days
    "day.today": "ഇന്ന്",
    "day.tomorrow": "നാളെ",
    "day.wednesday": "ബുധനാഴ്ച",
    "day.thursday": "വ്യാഴാഴ്ച",
    "day.friday": "വെള്ളിയാഴ്ച",
    "day.saturday": "ശനിയാഴ്ച",
    "day.sunday": "ഞായറാഴ്ച",
    
    // Weather Conditions
    "condition.sunny": "വെയിൽ",
    "condition.cloudy": "മേഘാവൃതം",
    "condition.partlyCloudy": "ഭാഗിക മേഘാവൃതം",
    "condition.rainy": "മഴ",
    
    // Advice
    "advice.irrigationTitle": "നീർവേലി നിർദ്ദേശം",
    "advice.irrigationText": "മണ്ണിന്റെ ഈർപ്പവും കാലാവസ്ഥാ പ്രവചനവും അടിസ്ഥാനമാക്കി, വിളകളുടെ മികച്ച വളർച്ചയ്ക്ക് നീരൊഴിക്കൽ ശുപാർശ ചെയ്യുന്നു.",
    "advice.pestAlertTitle": "കീട മുന്നറിയിപ്പ്",
    "advice.pestAlertText": "ഉയർന്ന ആർദ്രതാ നിലവാരം കീട പ്രവർത്തനം വർദ്ധിപ്പിച്ചേക്കാം. വിളകൾ സൂക്ഷ്മമായി നിരീക്ഷിക്കുകയും പ്രതിരോധ നടപടികൾ പരിഗണിക്കുകയും ചെയ്യുക.",
    "advice.harvestWindowTitle": "വിളവെടുപ്പ് സമയം",
    "advice.harvestWindowText": "അനുകൂല കാലാവസ്ഥാ സാഹചര്യങ്ങൾ പ്രതീക്ഷിക്കുന്നു. തയ്യാറായ വിളകൾ വിളവെടുക്കുന്നതിനുള്ള നല്ല സമയം.",
    "advice.fertilizerApplicationTitle": "വള പ്രയോഗം",
    "advice.fertilizerApplicationText": "കാലാവസ്ഥാ സാഹചര്യങ്ങൾ വള പ്രയോഗത്തിന് അനുയോജ്യമാണ്. പ്രതീക്ഷിക്കുന്ന മഴയ്ക്ക് മുമ്പ് പ്രയോഗിക്കുക.",
    
    // Weather Alerts
    "heavyRainAlertTitle": "കനത്ത മഴയുടെ മുന്നറിയിപ്പ്",
    "heavyRainAlertAdvice": "അടുത്ത 48 മണിക്കൂറിനുള്ളിൽ കനത്ത മഴ പ്രതീക്ഷിക്കുന്നു. ശരിയായ ഡ്രെയിനേജ് ഉറപ്പാക്കുകയും സെൻസിറ്റീവ് വിളകൾ സംരക്ഷിക്കുകയും ചെയ്യുക.",
    
    // Language
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    english: "English",
    hindi: "हिंदी",
    malayalam: "മലയാളം",

    // Farm Planning
    farmPlanningTitle: "കൃഷി ആസൂത്രണം",
    farmPlanningDesc: "മികച്ച വിളവിനായി നിങ്ങളുടെ വിളകളുടെയും കൃഷി പ്രവർത്തനങ്ങളുടെയും ആസൂത്രണം ചെയ്യുക",
    planningProcess: "ആസൂത്രണ പ്രക്രിയ",
    soilAnalysis: "മണ്ണ് വിശകലനം",
    soilAnalysisDesc: "മണ്ണിന്റെ പിഎച്ച്, പോഷകങ്ങൾ, ജൈവ പദാർത്ഥങ്ങൾ എന്നിവ പരിശോധിക്കുക",
    cropSelection: "വിള തിരഞ്ഞെടുക്കൽ",
    cropSelectionDesc: "മണ്ണിന്റെ തരവും കാലാവസ്ഥയും അടിസ്ഥാനമാക്കി വിളകൾ തിരഞ്ഞെടുക്കുക",
    resourcePlanning: "വിഭവ ആസൂത്രണം",
    resourcePlanningDesc: "ജലം, വളം, ഉപകരണങ്ങൾ എന്നിവയുടെ ആവശ്യകതകൾ ആസൂത്രണം ചെയ്യുക",
    scheduleCreation: "കാലക്രമം സൃഷ്ടിക്കൽ",
    scheduleCreationDesc: "നടീൽ, പരിചരണം, വിളവെടുപ്പ് എന്നിവയുടെ കാലക്രമം സൃഷ്ടിക്കുക",
    completed: "പൂർത്തിയായി",
    inProgress: "പുരോഗതിയിൽ",
    pending: "തീർപ്പുകൽപ്പിക്കാത്തത്",
    selectCrop: "വിള തിരഞ്ഞെടുക്കുക",
    chooseCrop: "ഒരു വിള തിരഞ്ഞെടുക്കുക",
    selectSeason: "സീസൺ തിരഞ്ഞെടുക്കുക",
    season: "സീസൺ",
    kharifMonsoon: "ഖരീഫ് (മൺസൂൺ)",
    rabiWinter: "റാബി (ശീതകാലം)",
    zaidSummer: "സായിദ് (വേനൽക്കാലം)",
    generatePlan: "പദ്ധതി തയ്യാറാക്കുക",
    cropInformation: "വിള വിവരങ്ങൾ",
    duration: "കാലാവധി",
    expectedYield: "പ്രതീക്ഷിക്കുന്ന വിളവ്",
    farmingCalendar: "കാർഷിക കലണ്ടർ",
    plantingSeason: "നടീൽ സീസൺ",
    growingSeason: "വളർച്ചാ സീസൺ",
    harvestSeason: "വിളവെടുപ്പ് സീസൺ",
    careMaintenance: "പരിചരണവും പരിപാലനവും",
    harvestStorage: "വിളവെടുപ്പും സംഭരണവും",
    
    // Disease Detection
    diseaseDetectionTitle: "രോഗ കണ്ടെത്തൽ",
    diseaseDetectionPageDesc: "AI-പവർഡ് രോഗ തിരിച്ചറിയലിനായി ചെടിയുടെ ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക",
    uploadPlantImage: "ചെടിയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    clickUploadDrag: "അപ്‌ലോഡ് ചെയ്യുന്നതിനായി ക്ലിക്ക് ചെയ്യുക അല്ലെങ്കിൽ ഡ്രാഗ് ചെയ്യുക",
    pngJpgLimit: "PNG, JPG 10MB വരെ",
    imageSelectedSuccessfully: "ചിത്രം വിജയകരമായി തിരഞ്ഞെടുത്തു",
    analyzeDisease: "രോഗ വിശകലനം ചെയ്യുക",
    analyzing: "വിശകലനം ചെയ്യുന്നു...",
    analysisResults: "വിശകലന ഫലങ്ങൾ",
    confidence: "ആത്മവിശ്വാസം",
    crop: "വിള",
    symptoms: "ലക്ഷണങ്ങൾ",
    treatment: "ചികിത്സ",
    prevention: "പ്രതിരോധം",
    uploadImageForAnalysis: "രോഗ വിശകലന ഫലങ്ങൾ ലഭിക്കാൻ ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    commonDiseases: "സാധാരണ രോഗങ്ങൾ",
    severity: "തീവ്രത",
    high: "ഉയർന്ന",
    medium: "ഇടത്തരം",
    low: "കുറഞ്ഞ",
    
    // Education
    farmEducationTitle: "കാർഷിക വിദ്യാഭ്യാസം",
    learnModernFarming: "ആധുനിക കൃഷി സാങ്കേതികതകളും മികച്ച രീതികളും പഠിക്കുക",
    courseCompletion: "കോഴ്സ് പൂർത്തീകരണം",
    certificatesEarned: "നേടിയ സർട്ടിഫിക്കറ്റുകൾ",
    studyHours: "പഠന മണിക്കൂറുകൾ",
    communityRank: "കമ്മ്യൂണിറ്റി റാങ്ക്",
    searchCourses: "കോഴ്സുകൾ തിരയുക...",
    allCourses: "എല്ലാ കോഴ്സുകളും",
    cropManagement: "വിള നിർവഹണം",
    technology: "സാങ്കേതികവിദ്യ",
    sustainability: "സുസ്ഥിരത",
    soilScience: "മൃത്തിക ശാസ്ത്രം",
    irrigation: "നീരൊഴിക്കൽ",
    diseaseControl: "രോഗ നിയന്ത്രണം",
    students: "വിദ്യാർത്ഥികൾ",
    startLearning: "പഠിക്കാൻ തുടങ്ങുക",
    joinExpertWebinar: "ഞങ്ങളുടെ വിദഗ്ധ വെബിനാറിൽ ചേരുക",
    futureOfAgriculture: "കൃഷിയുടെ ഭാവി: സാങ്കേതികവിദ്യയും സുസ്ഥിരതയും",
    liveSessionExperts: "വ്യവസായ വിദഗ്ധരുമായി ലൈവ് സെഷൻ • നാളെ ഉച്ചകഴിഞ്ഞ് 2:00 ന്",
    registerNow: "ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക",
    beginner: "തുടക്കക്കാരൻ",
    intermediate: "ഇടത്തരം",
    advanced: "ഉന്നത",
    
    // Marketplace
    marketplaceTitle: "മാർക്കറ്റ്പ്ലേസ്",
    buyAndSellProducts: "കർഷകരുമായി നേരിട്ട് കാർഷിക ഉൽപ്പന്നങ്ങൾ വാങ്ങുകയും വിൽക്കുകയും ചെയ്യുക",
    buyProducts: "ഉൽപ്പന്നങ്ങൾ വാങ്ങുക",
    myListings: "എന്റെ ലിസ്റ്റിംഗുകൾ",
    searchProducts: "ഉൽപ്പന്നങ്ങൾ തിരയുക...",
    all: "എല്ലാം",
    grains: "ധാന്യങ്ങൾ",
    vegetables: "പച്ചക്കറികൾ",
    fruits: "പഴങ്ങൾ",
    pulses: "പയർവർഗ്ഗങ്ങൾ",
    spices: "മസാലകൾ",
    perKg: "കിലോഗ്രാം",
    addToCart: "കാർട്ടിൽ ചേർക്കുക",
    outOfStock: "സ്റ്റോക്കിൽ ഇല്ല",
    myProductListings: "എന്റെ ഉൽപ്പന്ന ലിസ്റ്റിംഗുകൾ",
    addNewProduct: "പുതിയ ഉൽപ്പന്നം ചേർക്കുക",
    views: "കാഴ്ചകൾ",
    inquiries: "അന്വേഷണങ്ങൾ",
    editListing: "ലിസ്റ്റിംഗ് എഡിറ്റ് ചെയ്യുക",
    viewAnalytics: "അനാലിറ്റിക്സ് കാണുക",
    salesOverview: "വിൽപ്പന അവലോകനം",
    activeListings: "സജീവ ലിസ്റ്റിംഗുകൾ",
    totalViews: "മൊത്തം കാഴ്ചകൾ",
    revenueThisMonth: "ഈ മാസത്തെ വരുമാനം",
    
    // Government
    governmentSchemesTitle: "സർക്കാർ പദ്ധതികൾ",
    accessGovernmentPrograms: "കർഷകർക്കുള്ള സർക്കാർ പ്രോഗ്രാമുകളും സാമ്പത്തിക സഹായവും ആക്സസ് ചെയ്യുക",
    myApplications: "എന്റെ അപേക്ഷകൾ",
    applicationId: "അപേക്ഷാ നമ്പർ",
    submitted: "സമർപ്പിച്ചത്",
    approved: "അനുമോദിതം",
    processing: "പ്രോസസ്സിംഗ്",
    amount: "തുക",
    deadline: "അവസാന തീയതി",
    eligibility: "യോഗ്യത",
    keyBenefits: "പ്രധാന ആനുകൂല്യങ്ങൾ",
    applyNow: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    quickLinks: "ദ്രുത ലിങ്കുകൾ",
    allSchemes: "എല്ലാ പദ്ധതികളും",
    subsidies: "സബ്സിഡികൾ",
    insurance: "ഇൻഷുറൻസ്",
    credit: "വായ്പ",
    marketSupport: "മാർക്കറ്റ്",
    limitedTime: "പരിമിത സമയം",
    
    // Profile
    myProfile: "എന്റെ പ്രൊഫൈൽ",
    manageAccountInfo: "നിങ്ങളുടെ അക്കൗണ്ട് വിവരങ്ങളും കാർഷിക വിശദാംശങ്ങളും നിയന്ത്രിക്കുക",
    editProfile: "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
    saveChanges: "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
    personalInformation: "വ്യക്തിഗത വിവരങ്ങൾ",
    memberSince: "അംഗമായത്",
    verifiedFarmer: "സാക്ഷ്യപ്പെടുത്തിയ കർഷകൻ",
    fullName: "മുഴുവൻ പേര്",
    yourFirstName: "നിങ്ങളുടെ ആദ്യ പേര്",
    yourLastName: "നിങ്ങളുടെ അവസാന പേര്",
    email: "ഇമെയിൽ",
    phone: "ഫോൺ",
    farmSize: "കാർഷിക ഭൂമിയുടെ വലുപ്പം",
    location: "സ്ഥാനം",
    mainCrops: "പ്രധാന വിളകൾ",
    experience: "പരിചയം",
    achievements: "നേട്ടങ്ങൾ",
    bestFarmerAward: "മികച്ച കർഷക പുരസ്കാരം",
    organicCertification: "ഓർഗാനിക് സർട്ടിഫിക്കേഷൻ",
    highYieldAchievement: "ഉയർന്ന വിളവ് നേട്ടം",
    performanceStatistics: "പ്രകടന സ്ഥിതിവിവരക്കണക്കുകൾ",
    totalHarvest: "മൊത്തം വിളവ്",
    thisYear: "ഈ വർഷം",
    revenue: "വരുമാനം",
    coursesCompleted: "പൂർത്തിയാക്കിയ കോഴ്സുകൾ",
    allTime: "എല്ലാ കാലത്തും",
    recentActivitiesProfile: "സമീപകാല പ്രവർത്തനങ്ങൾ",
    
    // Support
    supportCenter: "പിന്തുണാ കേന്ദ്രം",
    getHelpAndAnswers: "സഹായം നേടുകയും നിങ്ങളുടെ ചോദ്യങ്ങൾക്ക് ഉത്തരം കണ്ടെത്തുകയും ചെയ്യുക",
    phoneSupport: "ഫോൺ സപ്പോർട്ട്",
    getImmediateHelp: "ഞങ്ങളുടെ വിദഗ്ധരിൽ നിന്ന് ഉടനടി സഹായം നേടുക",
    available24x7: "24/7 ലഭ്യം",
    emailSupport: "ഇമെയിൽ സപ്പോർട്ട്",
    sendDetailedQueries: "ഞങ്ങൾക്ക് വിശദമായ ചോദ്യങ്ങൾ അയയ്ക്കുക",
    responseWithin24h: "24 മണിക്കൂറിനുള്ളിൽ പ്രതികരണം",
    liveChat: "ലൈവ് ചാറ്റ്",
    chatWithSupportTeam: "ഞങ്ങളുടെ പിന്തുണാ ടീമുമായി ചാറ്റ് ചെയ്യുക",
    startChat: "ചാറ്റ് ആരംഭിക്കുക",
    businessHours: "രാവിലെ 9 മുതൽ വൈകുന്നേരം 6 വരെ IST",
    faq: "FAQ",
    myTickets: "എന്റെ ടിക്കറ്റുകൾ",
    createTicket: "ടിക്കറ്റ് സൃഷ്ടിക്കുക",
    searchFaq: "പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ തിരയുക...",
    mySupportTickets: "എന്റെ പിന്തുണാ ടിക്കറ്റുകൾ",
    ticketId: "ടിക്കറ്റ് നമ്പർ",
    created: "സൃഷ്ടിച്ചത്",
    lastUpdated: "അവസാനം അപ്ഡേറ്റ് ചെയ്തത്",
    createSupportTicket: "പിന്തുണാ ടിക്കറ്റ് സൃഷ്ടിക്കുക",
    subject: "വിഷയം",
    briefDescription: "നിങ്ങളുടെ പ്രശ്നത്തിന്റെ ഹ്രസ്വ വിവരണം",
    category: "വിഭാഗം",
    selectCategory: "ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക",
    technicalIssue: "സാങ്കേതിക പ്രശ്നം",
    billing: "ബില്ലിംഗ്",
    featureRequest: "ഫീച്ചർ അഭ്യർത്ഥന",
    generalInquiry: "പൊതു അന്വേഷണം",
    priority: "മുൻഗണന",
    description: "വിവരണം",
    describeIssueDetail: "ദയവായി നിങ്ങളുടെ പ്രശ്നം വിശദമായി വിവരിക്കുക...",
    open: "തുറന്ന",
    resolved: "പരിഹരിച്ചു",
    
    // Contact Us
    contactUsTitle: "ബന്ധപ്പെടുക",
    getInTouchWithTeam: "പിന്തുണയ്ക്കും അന്വേഷണങ്ങൾക്കും ഞങ്ങളുടെ ടീമുമായി ബന്ധപ്പെടുക",
    sendMessage: "ഞങ്ങൾക്ക് ഒരു സന്ദേശം അയയ്ക്കുക",
    firstName: "ആദ്യ പേര്",
    lastName: "അവസാന പേര്",
    yourEmail: "നിങ്ങളുടെ.ഇമെയിൽ@ഉദാഹരണം.com",
    phoneNumber: "+91 XXXXX XXXXX",
    messageSubject: "നിങ്ങളുടെ സന്ദേശം എന്തിനെക്കുറിച്ചാണ്?",
    messageText: "എങ്ങനെ സഹായിക്കാമെന്ന് ഞങ്ങളോട് പറയുക...",
    sendMessageBtn: "സന്ദേശം അയയ്ക്കുക",
    contactInformation: "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
    headquarters: "ആസ്ഥാനം",
    phoneSupportContact: "ഫോൺ സപ്പോർട്ട്",
    emailSupportContact: "ഇമെയിൽ സപ്പോർട്ട്",
    businessHoursContact: "ബിസിനസ് മണിക്കൂർ",
    meetOurTeam: "ഞങ്ങളുടെ ടീമിനെ കാണുക",
    emergencySupport: "അടിയന്തിര കാർഷിക സഹായം",
    urgentFarmingEmergencies: "അടിയന്തിര കാർഷിക അത്യാഹിതങ്ങൾക്കും ദുരന്തങ്ങൾക്കും",
    emergencyHotline: "അടിയന്തര ഹോട്ട്‌ലൈൻ: 1800-XXX-EMERGENCY",
    findUs: "ഞങ്ങളെ കണ്ടെത്തുക",
    interactiveMapComingSoon: "ഇൻറ്ററാക്ടീവ് മാപ്പ് ഉടൻ വരുന്നു",
    
    // Chatbot
    chatbotTitle: "കൃഷി AI അസിസ്റ്റന്റ്",
    onlineReadyToHelp: "ഓൺലൈൻ • സഹായിക്കാൻ തയ്യാർ",
    krishiAiGreeting: "ഹലോ! ഞാൻ കൃഷി AI ആണ്, നിങ്ങളുടെ കാർഷിക സഹായി. ഇന്ന് എങ്ങനെ സഹായിക്കാം?",
    weatherUpdate: "കാലാവസ്ഥാ അപ്ഡേറ്റ്",
    cropAdvice: "വിള ഉപദേശം",
    marketPrices: "മാർക്കറ്റ് വിലകൾ",
    diseaseHelp: "രോഗ സഹായം",
    askAnything: "കൃഷിയെക്കുറിച്ച് എന്തും ചോദിക്കുക...",
    farmingTips: "കാർഷിക ടിപ്പുകൾ",
    
    // Registration
    completeProfile: "നിങ്ങളുടെ പ്രൊഫൈൽ പൂർത്തിയാക്കുക",
    personalizeExperience: "നിങ്ങളുടെ കൃഷി സേവാ അനുഭവം വ്യക്തിഗതമാക്കുന്നതിനായി നിങ്ങളെക്കുറിച്ച് ഞങ്ങളോട് പറയുക",
    profileSetup: "പ്രൊഫൈൽ സെറ്റപ്പ്",
    chooseYourRole: "നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക",
    farmer: "കർഷകൻ",
    admin: "അഡ്മിൻ",
    retailer: "റീട്ടെയിലർ",
    labourer: "തൊഴിലാളി",
    agriculturalProducer: "കാർഷിക ഉത്പാദകനും കൃഷിക്കാരനും",
    systemAdministrator: "സിസ്റ്റം അഡ്മിനിസ്ട്രേറ്ററും മാനേജറും",
    businessOwnerSeller: "ബിസിനസ് ഉടമയും വിൽപ്പനക്കാരനും",
    agriculturalWorker: "കാർഷിക തൊഴിലാളിയും സഹായിയും",
    profileUpdatedSuccessfully: "പ്രൊഫൈൽ വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു! നിങ്ങളുടെ വിവരങ്ങൾ സേവ് ചെയ്തിരിക്കുന്നു.",
    errorUpdatingProfile: "നിങ്ങളുടെ പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പിശകുണ്ടായി. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    emailRequired: "ഇമെയിൽ ആവശ്യമാണ്",
    validEmailRequired: "ദയവായി സാധുവായ ഇമെയിൽ വിലാസം നൽകുക",
    phoneRequired: "ഫോൺ നമ്പർ ആവശ്യമാണ്",
    businessNameRequired: "ബിസിനസ് പേര് ആവശ്യമാണ്",
    businessTypeRequired: "ബിസിനസ് തരം ആവശ്യമാണ്",
    farmerNameRequired: "പേര് ആവശ്യമാണ്",
    savingProfile: "പ്രൊഫൈൽ സേവ് ചെയ്യുന്നു...",
    saveProfile: "പ്രൊഫൈൽ സേവ് ചെയ്യുക",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('krishiSevaLanguage');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('krishiSevaLanguage', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
